;/*FB_PKG_DELIM*/

__d("MLCHealthLoggerEvent",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({DAILY_INTERACTION_WITH_SURFACE:"daily_interaction_with_surface",COMMIT_CREATE:"commit_create",COMMIT_EDIT:"commit_edit"});c=a;f["default"]=c}),66);
__d("MLCInstrumentationCommands",["Lexical"],(function(a,b,c,d,e,f,g){"use strict";a=d("Lexical").createCommand();b=d("Lexical").createCommand();c=d("Lexical").createCommand();e=d("Lexical").createCommand();g.COMMIT_COMMAND=a;g.INTERACTION_INSTRUMENTATION_READY=b;g.DOCUMENT_COMMAND=c;g.PLUGIN_EVENT_COMMAND=e}),98);
__d("MlcHealthBizappEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("2646");c=b("FalcoLoggerInternal").create("mlc_health_bizapp_event",a);e.exports=c}),null);
__d("MlcHealthCareerProfileEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("3833");c=b("FalcoLoggerInternal").create("mlc_health_career_profile_event",a);e.exports=c}),null);
__d("MlcHealthFacebookAndWorkplaceEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("2647");c=b("FalcoLoggerInternal").create("mlc_health_facebook_and_workplace_event",a);e.exports=c}),null);
__d("MlcHealthFacebookEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("2648");c=b("FalcoLoggerInternal").create("mlc_health_facebook_event",a);e.exports=c}),null);
__d("MlcHealthInstagramEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("3766");c=b("FalcoLoggerInternal").create("mlc_health_instagram_event",a);e.exports=c}),null);
__d("MlcHealthInternalToolsEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("2649");c=b("FalcoLoggerInternal").create("mlc_health_internal_tools_event",a);e.exports=c}),null);
__d("MlcHealthMessagingLightswitchEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("2650");c=b("FalcoLoggerInternal").create("mlc_health_messaging_lightswitch_event",a);e.exports=c}),null);
__d("MlcHealthWorkplaceEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("2651");c=b("FalcoLoggerInternal").create("mlc_health_workplace_event",a);e.exports=c}),null);
__d("MLCHealthInstrumentationPlugin__INTERNAL.react",["FBLogger","Lexical","LexicalComposerContext","LexicalUtils","MLCInstrumentationCommands","MlcHealthBizappEventFalcoEvent","MlcHealthCareerProfileEventFalcoEvent","MlcHealthFacebookAndWorkplaceEventFalcoEvent","MlcHealthFacebookEventFalcoEvent","MlcHealthInstagramEventFalcoEvent","MlcHealthInternalToolsEventFalcoEvent","MlcHealthMessagingLightswitchEventFalcoEvent","MlcHealthWorkplaceEventFalcoEvent","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useLayoutEffect,i=new Set();function j(a){switch(a){case"facebook":return c("MlcHealthFacebookEventFalcoEvent");case"workplace":return c("MlcHealthWorkplaceEventFalcoEvent");case"facebook_and_workplace":return c("MlcHealthFacebookAndWorkplaceEventFalcoEvent");case"internal_tools":return c("MlcHealthInternalToolsEventFalcoEvent");case"messaging_lightswitch":return c("MlcHealthMessagingLightswitchEventFalcoEvent");case"bizapp":return c("MlcHealthBizappEventFalcoEvent");case"instagram":return c("MlcHealthInstagramEventFalcoEvent");case"career_profile":return c("MlcHealthCareerProfileEventFalcoEvent");default:a}throw c("FBLogger")("lexical").mustfixThrow("Policy product not handled by exhaustive switch-case?")}function k(a,b,c){j(a).log(function(){return{event:c,surface:b}})}function a(a){var b=a.editor__DEPRECATED,c=a.policyProduct,e=a.surface,f;if(b)f=b;else{a=d("LexicalComposerContext").useLexicalComposerContext();f=a[0]}h(function(){var a=function(){};i.has(e)||(a=f.registerUpdateListener(function(b){var d=b.dirtyLeaves;b=b.tags;if(i.has(e)){a();return}if(d.size===0||b.has("history-merge")||!f.isEditable())return;i.add(e);k(c,e,"daily_interaction_with_surface");a()}));return d("LexicalUtils").mergeRegister(a,f.registerCommand(d("MLCInstrumentationCommands").COMMIT_COMMAND,function(a){a==="create"?k(c,e,"commit_create"):k(c,e,"commit_edit");return!1},d("Lexical").COMMAND_PRIORITY_CRITICAL))},[f,c,e]);return null}g["default"]=a}),98);
__d("MLCInteractionInstrumentationPlugin__INTERNAL.react",["cr:3286","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){return b("cr:3286")&&h.jsx(b("cr:3286"),babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("MLCTypingPerformancePlugin__INTERNAL.react",["LexicalComposerContext","cr:2012305","cr:308","cr:3287","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i=d("react").useLayoutEffect,j=b("cr:2012305")||b("cr:308");function a(a){if(j===null)return null;b("cr:3287")&&b("cr:3287")();return h.jsx(k,babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";function k(a){var b=a.editor__DEPRECATED,c=a.format__DEPRECATED,e=a.surface;a=a.typingPerformanceID;var f=a===void 0?"":a,g;if(b)g=b;else{a=d("LexicalComposerContext").useLexicalComposerContext();g=a[0]}i(function(){if(j===null)return;var a=null,b=g.registerRootListener(function(b){if(b===a)return;a!==null&&j.unregisterTypingPerf(a);if(b!==null){var d;j.trackTypingPerf(b,e,a,{editor:"LexicalEditor",format:(d=c)!=null?d:"",typingPerformanceID:f})}a=b});return function(){b(),a!==null&&j.unregisterTypingPerf(a)}},[f,g,c,e]);return null}g["default"]=a}),98);
__d("MLCInstrumentationPlugin__INTERNAL.react",["MLCHealthInstrumentationPlugin__INTERNAL.react","MLCInteractionInstrumentationPlugin__INTERNAL.react","MLCTypingPerformancePlugin__INTERNAL.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");b="facebook";b;function a(a){return h.jsxs(h.Fragment,{children:[h.jsx(c("MLCTypingPerformancePlugin__INTERNAL.react"),babelHelpers["extends"]({},a)),h.jsx(c("MLCHealthInstrumentationPlugin__INTERNAL.react"),babelHelpers["extends"]({},a)),h.jsx(c("MLCInteractionInstrumentationPlugin__INTERNAL.react"),babelHelpers["extends"]({},a))]})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);